### ISSUE TITLE
gearの登録

### ISSUE THREAD

**Issue by aMasakiTakahashi** [aAkioFujita/stackoverflow_clone_fujita#10]
下記を実施する。

* AC console用のアカウントのgoogle group作成する。
  * [ここ](https://groups.google.com/a/access-company.com/forum/?hl=ja#!overview)から作成
  * アドレスは`stackoverflow_clone_fujita_a-gr @ access-company.com`
  * メンバーに高橋を追加
  * 権限 => 投稿権限を「一般公開」に設定
* AC console用のアカウント
  * [ここ](https://ac-console.solomon.access-company.com/signup)から先程のgoogle groupをIDにしてアカウントを作成
  * passwordはgoogle spreadsheet上に記載して、githubのrepositoryのREADMEにアカウント情報は上記のspreadsheetに記載してあることを書き、リンクさせる
  * このspreadsheetを`stackoverflow_clone_fujita_a-gr @ access-company.com`に対して共有設定する。
* Dodai appの作成
  * AC console上でdodaiアプリを作成する
  * 名前はgearと同名
* gearの登録
  * AC console上でgearを登録する。
  * 名前はgithubのrepository名と同じ

**Comment by aMasakiTakahashi** [comment]
@aAkioFujita 
自分がACCESSにいない日もあるので、gearの作成手順などをこのissueに書いておきました。
必要になりましたら作業ください。
もし分からない点などがありましたらご質問いただければと思います。

**Comment by aMasakiTakahashi** [comment]
@aAkioFujita 

下記のエラーメッセージの通り、deployが失敗しています。
これは、solomonのauto deploy機構が、このレポジトリからcloneしようとして失敗したことの通知になります。
このrepositoryに対して、write権限をgithub上の「solomon」チームに追加していただけますか？

```
See <https://ac-console.solomon.access-company.com/jenkins/job/stackoverflow_fujita/1/display/redirect> 

------------------------------------------ 
Started by an SCM change 
Building in workspace <https://ac-console.solomon.access-company.com/jenkins/job/stackoverflow_fujita/ws/> 
Cloning the remote Git repository 
Cloning repository git@github.com:access-company/stackoverflow_fujita.git 
 > git init <https://ac-console.solomon.access-company.com/jenkins/job/stackoverflow_fujita/ws/> # timeout=10 
Fetching upstream changes from git@github.com:access-company/stackoverflow_fujita.git 
 > git --version # timeout=10 
 > git fetch --tags --progress git@github.com:access-company/stackoverflow_fujita.git +refs/heads/*:refs/remotes/origin/* 
ERROR: Error cloning remote repo 'origin' 
hudson.plugins.git.GitException: Command "git fetch --tags --progress git@github.com:access-company/stackoverflow_fujita.git +refs/heads/*:refs/remotes/origin/*" returned status code 128: 
stdout: 
stderr: ERROR: Repository not found. 
fatal: Could not read from remote repository. 

Please make sure you have the correct access rights 
and the repository exists. 

        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996) 
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1715) 
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72) 
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405) 
        at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:614) 
        at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1120) 
        at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160) 
        at hudson.scm.SCM.checkout(SCM.java:504) 
        at hudson.model.AbstractProject.checkout(AbstractProject.java:1203) 
        at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574) 
        at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86) 
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499) 
        at hudson.model.Run.execute(Run.java:1727) 
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43) 
        at hudson.model.ResourceController.execute(ResourceController.java:97) 
        at hudson.model.Executor.run(Executor.java:429) 
ERROR: Error cloning remote repo 'origin' 
```

**Comment by aAkioFujita** [comment]
上記確認したところ、gearの登録で参照されるようになるリポジトリが以下のようになっており、変更できないようなのですが、access-companyアカウント内にリポジトリを作成する必要があるのでしょうか。
git@github.com:access-company/your_gear_name.git

**Comment by aMasakiTakahashi** [comment]
こちらの残作業は下記

>passwordはgoogle spreadsheet上に記載して、githubのrepositoryのREADMEにアカウント情報は上記のspreadsheetに記載してあることを書き、リンクさせる
